### ISSUE TITLE
Error during exit

### ISSUE THREAD

**Issue by pholasek** [garncarz/laileoulacuisse#9]
When leaving _laileoulacuisse_ app by Quit button in menu, following error appeared in terminal:
`Exception ignored in: <bound method PluginSource.__del__ of <pluginbase.PluginSource object at 0x7fd6bf9e7320>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 247, in __del__
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 303, in cleanup
  File "/usr/lib/python3.4/site-packages/pluginbase.py", line 318, in __cleanup
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`

**Comment by garncarz** [comment]
Thanks for reporting, it seems like a (fortunately non blocking) bug in the [PluginBase](http://pluginbase.pocoo.org/) library. I've already reported it here: https://github.com/mitsuhiko/pluginbase/issues/7.

**Comment by garncarz** [comment]
[PluginBase version 0.5](https://github.com/mitsuhiko/pluginbase/releases/tag/0.5) fixes it.
